config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'


  resources :projects#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  # get 'delete_project', to: 'projects#destroy_a'


  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  # get 'delete_user', to: 'users#destroy_a'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'


  resources :bugs, except: [:destroy]
  # Defines the root path route ("/")
  # root "projects#index"
end

app/views/pages/about.html.erb
<h1 class = "text-center"> This is ABOUT Page! </h1>

<%= link_to 'Projects Listing Page', projects_path%> | <%= link_to 'Home Page', root_path%>

app/views/pages/home.html.erb
  <h1 class = "text-center"> This is Home Page! </h1>
  <div class="container" id = "home-container">
    <div class="mt-4 p-5 jumbotron bg-primary text-center text-white rounded">
      <h1 class= "text-center"> Bugzilla</h1>
      <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic ab
          repellat voluptatibus fugiat debitis fugit similique dolorum, vel
          nihil reiciendis voluptatem saepe nobis quia minima fuga. Voluptates
          debitis ratione vel.
      </p>
      <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
  <%= link_to 'Projects Listing Page', projects_path%> | <%= link_to 'About Page', about_path%>