config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'


  resources :projects#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  # get 'delete_project', to: 'projects#destroy_a'


  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  # get 'delete_user', to: 'users#destroy_a'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'


  resources :bugs, except: [:destroy]
  # Defines the root path route ("/")
  # root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    
    has_many :bug_projects
    has_many :bugs, through: :bug_projects

    validates :title, presence: true, length: {minimum: 3, maximum: 30}
    validates :description, presence: true, length: {minimum: 5, maximum: 400}
end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
		before_action :require_user, except: [:show, :index]
		before_action :require_same_user, only: [:edit, :update, :destroy]
		before_action :authorize_manager, only: [:new, :create]


		def show
        # debugger
				# binding.break # Call to debugger
    end

    def index
        @projects = Project.paginate(page: params[:page], per_page: 5)
    end

    def new
			@project = Project.new
    end

		def edit
		end

    def create
        @project = Project.new(project_params)
				# @project.user = User.first    #added temporarily
				@project.user = current_user
        if @project.save
					flash[:notice] = "Project was created successfully!"
        	redirect_to project_path(@project)
				else
					flash[:notice] = "Failed to create project!"
					#render 'new'
					render 'new', status: :unprocessable_entity
				end
        #render plain: @project.inspect
    end

		def update
			if @project.update(project_params)
				flash[:notice] = "Project was updated successfully!"
				redirect_to project_path(@project)
			else
				flash[:notice] = "Failed to update the project!"
				render 'edit', status: :unprocessable_entity
			end
		end

		def destroy
			@project.destroy
			redirect_to projects_path
		end

		# def destroy_a
		# 	project = Project.find_by(id: params[:id])
		# 	project.destroy
		# 	redirect_to projects_path
		# end


		



		private
		def set_project
			@project = Project.find(params[:id])
		end

		def project_params
			params.require(:project).permit(:title, :description)
		end

		def require_same_user
			if current_user != @project.user && !current_user.admin?
				flash[:alert] = "You can only edit or delete your own project, or the manager have this access"
				redirect_to @project
			end
		end

		def authorize_manager
			redirect_to root_path, alert: 'Only managers can create projects.' unless current_user.manager?
		end

end

app/views/projects/_form.html.erb
<div class="container">


  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @project %>
      <%= form_with(model: @project, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group mb-2 row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of project" %>
          </div>
        </div>
        <div class="form-group mb-2 row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded ", placeholder: "Description of project" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Return to Projects Listing Page ]', projects_path, class: "text-info text-center" %>
  </div>

</div>

app/views/projects/_project.html.erb
<div class="container">
  <% @projects.each do |project| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if project.user %>
              created by <%= link_to project.user.username, user_path(project.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to project.title, project_path(project), class: "text-success text-decoration-none" %></h5>
            <p class="card-text"><%= truncate(project.description, length: 25) %></p>
            <%= link_to 'View', project_path(project), class: "btn btn-outline-success" %>
            <% if logged_in? && (project.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_project_path(project), class: "btn btn-outline-info" %>
              <%= link_to 'Delete', project_path(project.id), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created <%= time_ago_in_words(project.created_at) %> ago,
              Updated <%= time_ago_in_words(project.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<table>
    <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= truncate(project.description, length: 25) %></td>
          <td><%= link_to 'Show', project_path(project) %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Delete', project_path(project.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<p class = "ms-4">
  <%= link_to 'Create a new project', new_project_path, class: "btn btn-outline-success" %>
</p>

app/views/projects/edit.html.erb
  <h1 class= "text-center mt-4">Edit project</h1>

  <%= render 'form' %>

app/views/projects/index.html.erb
<h1 class= "text-center mt-4">Listing all projects</h1>

<div class="flickr_pagination">
    <%= will_paginate @projects, :container => false %>
</div>
<%= render 'project' %>
<div class="flickr_pagination mb-4">
    <%= will_paginate @projects, :container => false %>
</div>

app/views/projects/new.html.erb
<h1 class= "text-center mt-4">Create New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1 class= "text-center text-primary mt-4"><%= @project.title %></h1>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4 text-center">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          created by <%= @project.user.username if @project.user %>
          <%= link_to gravatar_for(@project.user), user_path(@project.user) %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@project.description) %></div>
          <% if logged_in? && (@project.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', project_path(@project.id), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>
            Created <%= time_ago_in_words(@project.created_at) %> ago,
            Updated <%= time_ago_in_words(@project.updated_at) %> ago
          </small>
        </div>
      </div>
      <%= link_to '[ Return to Projects Listing Page ]', projects_path, class: "text-danger" %>
    </div>
  </div>
</div>